name: FourElements
version: 'Alpha-0.0.1'
main: com.github.manu585.fourelements.bukkit.FourElementsPlugin
description: Minecraft bending plugin inspired by Avatar the last Airbender.
api-version: '26.1.2'
author: Manunu_
website: https://gogg-tech.com
database: true
libraries:
  - com.mysql:mysql-connector-j:9.2.0
  - com.zaxxer:HikariCP:6.2.1

dependencies:
  server:
    packetevents:
      load: BEFORE
      required: true
      join-classpath: true

permissions:
  fourelements.*:
    description: FourElements OP
    default: op
    children:
      fourelements.command.*: true
      fourelements.element.*: true

  fourelements.command.*:
    description: all /elements subcommands
    default: op
    children:
      fourelements.command.who: true
      fourelements.command.choose: true

  fourelements.command.who:
    description: view a players elements and other metadata
    default: true
  fourelements.command.choose:
    description: ability to pick an element
    default: op

  fourelements.element.*:
    description: access to all elements
    default: false
    children:
      fourelements.element.air: true
      fourelements.element.water: true
      fourelements.element.earth: true
      fourelements.element.fire: true